MEGAKINO-36 - Добавить метод в ActiveMerchant для запроса деталей
SecretAgents/active_merchant pull request #1
Opened 2023-08-07 09:16 UTC by vzdrizhni

2023-08-07 09:23 UTC, Syabr approved these changes

2023-08-07 09:25 UTC, KoshmareG approved these changes

2023-08-07 10:39 UTC, Creskiv requested changes

2023-08-07 10:39 UTC, Creskiv commented on lib/active_merchant/billing/gateways/abr_russia.rb
> +          elsif (node.to_xml.include?('OrderParams'))
А ты уверен вообще в этих действиях? У тебя там в node что именно лежит? Пример напиши

2023-08-07 11:02 UTC, vzdrizhni commented on lib/active_merchant/billing/gateways/abr_russia.rb
> +          elsif (node.to_xml.include?('OrderParams'))
Я взял пример из документации. Проверил xml из ответов 'CreateOrder' и 'GetOrderStatus', они парсятся нормально. Дело в количестве вложенных элементов. Пример из 'GetOrderInformation' после парсинга выглядит так:
```
`{:operation=>"GetOrderInformation", :status=>"00", :order_row=>"\n                477739\n                E60F2F4D759F85D1FA90AE3654C53198\n                2019-10-29 12:23:47\n                2019-10-29 12:30:16\n                2019-10-29 12:24:07\n                99900000\n                931\n                643\n                RU\n                testDesc\n                https://twpg-shop.abr.ru/index.php?action=handler\n                https://twpg-shop.abr.ru/index.php?action=handler\n                https://twpg-shop.abr.ru/index.php?action=handler\n                REVERSED\n                \n                496265998\n                0\n                null\n                0\n                Purchase\n                \n                0\n                \n                0000-00-00 00:00:00\n                191029\n                122407\n                \n                    \n                        PAN\n                        426810******9256\n                    \n                    \n                        PGSettings\n                        \n                    \n                    \n                        TWOResponseCode\n                        001\n                    \n                    \n                        POS_CAVV\n                        null\n                    \n                    \n                        XMLOUT\n                        \n                    \n                    \n                        CardHolderName\n                        L D\n                    \n                    \n                        CardBrand\n                        VISA\n                    \n                    \n                        RRN\n                        496265983\n                    \n                    \n                        APPROVAL\n                        085194\n                    \n                    \n                        ResponseDescription\n                        Удачное выполнение транзакции\n                    \n                    \n                        recurSlipNumber\n                        0\n                    \n                    \n                        InitialRRN\n                        496265983\n                    \n                    \n                        OrderPANHash\n                        F951BD8CC1F836DC9D6C4DDCB39882DAF47B5759539D3524FAA8F6901ADBC621\n                    \n                    \n                        Response_h\n                        0010011020\n                    \n                    \n                        Response_S\n                        477739          \n                    \n                    \n                        CAVV_RC\n                        12\n                    \n                    \n                        DescriptionHtml\n                                            test                \n                    \n                    \n                        feeCalculationResult\n                        0\n                    \n                    \n                        POS_eci\n                        87\n                    \n                \n                \n                    \n                        161\n                        2019-10-29 12:24:07\n                        99900000\n                        99900000\n                        11\n                        Purchase\n                        477739\n                        931\n                        643\n                        085194\n                        496265983\n                        001\n                        0\n                    \n                    \n                        161\n                        2019-10-29 12:30:16\n                        99900000\n                        99900000\n                        21\n                        Reverse\n                        477739\n                        931\n                        \n                        \n                        496265998\n                        001\n                        0\n                    \n                    \n                        160\n                        2019-10-29 12:23:47\n                        99900000\n                        null\n                        0\n                        CreateOrder\n                        477739\n                        0\n                        \n                        \n                        \n                        \n                        0\n                    \n                \n                \n                    \n                        \n                        \n                        \n                        \n                        \n                        \n                        \n                    \n                \n            "}`

Пример того, что лежит в node:
`#<Nokogiri::XML::Element:0x2aed7fb0b264 name="Order" children=[#<Nokogiri::XML::Text:0x2aed7f2dede8 "\n            ">, #<Nokogiri::XML::Element:0x2aed7f2ded34 name="row" children=[#<Nokogiri::XML::Text:0x2aed7f2deb54 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f2deaa0 name="id" children=[#<Nokogiri::XML::Text:0x2aed7f2de8c0 "477739">]>, #<Nokogiri::XML::Text:0x2aed7f2de71c "\n                ">, #<Nokogiri::XML::Element:0x2aed7f2de668 name="SessionID" children=[#<Nokogiri::XML::Text:0x2aed7f2de488 "E60F2F4D759F85D1FA90AE3654C53198">]>, #<Nokogiri::XML::Text:0x2aed7f2de2e4 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f2de230 name="createDate" children=[#<Nokogiri::XML::Text:0x2aed7f2de050 "2019-10-29 12:23:47">]>, #<Nokogiri::XML::Text:0x2aed7f299e78 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f299dc4 name="lastUpdateDate" children=[#<Nokogiri::XML::Text:0x2aed7f299be4 "2019-10-29 12:30:16">]>, #<Nokogiri::XML::Text:0x2aed7f299a40 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f29998c name="payDate" children=[#<Nokogiri::XML::Text:0x2aed7f2997ac "2019-10-29 12:24:07">]>, #<Nokogiri::XML::Text:0x2aed7f299608 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f299554 name="MerchantID" children=[#<Nokogiri::XML::Text:0x2aed7f299374 "99900000">]>, #<Nokogiri::XML::Text:0x2aed7f2991d0 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f29911c name="Amount" children=[#<Nokogiri::XML::Text:0x2aed7f298f3c "931">]>, #<Nokogiri::XML::Text:0x2aed7f298d98 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f298ce4 name="Currency" children=[#<Nokogiri::XML::Text:0x2aed7f298b04 "643">]>, #<Nokogiri::XML::Text:0x2aed7f298960 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f2988ac name="OrderLanguage" children=[#<Nokogiri::XML::Text:0x2aed7f2986cc "RU">]>, #<Nokogiri::XML::Text:0x2aed7f298528 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f298474 name="Description" children=[#<Nokogiri::XML::Text:0x2aed7f298294 "testDesc">]>, #<Nokogiri::XML::Text:0x2aed7f2980f0 "\n                ">, #<Nokogiri::XML::Element:0x2aed7f29803c name="ApproveURL" children=[#<Nokogiri::XML::Text:0x2aed80043e34 "https://twpg-shop.abr.ru/index.php?action=handler">]>, #<Nokogiri::XML::Text:0x2aed80043c90 "\n                ">, #<Nokogiri::XML::Element:0x2aed80043bdc name="CancelURL" children=[#<Nokogiri::XML::Text:0x2aed800439fc "https://twpg-shop.abr.ru/index.php?action=handler">]>, #<Nokogiri::XML::Text:0x2aed80043858 "\n                ">, #<Nokogiri::XML::Element:0x2aed8004377c name="DeclineURL" children=[#<Nokogiri::XML::Text:0x2aed8004340c "https://twpg-shop.abr.ru/index.php?action=handler">]>, #<Nokogiri::XML::Text:0x2aed80043114 "\n                ">, #<Nokogiri::XML::Element:0x2aed80042fd4 name="Orderstatus" children=[#<Nokogiri::XML::Text:0x2aed80042d54 "REVERSED">]>, #<Nokogiri::XML::Text:0x2aed80042bb0 "\n                ">, #<Nokogiri::XML::Element:0x2aed8 [...]

2023-08-07 11:48 UTC, Creskiv commented on lib/active_merchant/billing/gateways/abr_russia.rb
> +          elsif (node.to_xml.include?('OrderParams'))
Как это основываясь на документацию? У тебя что, запрос не проходит что ли что ты только по документации работаешь?
Это всё выше находится в node до выполнения to_xml?

2023-08-07 11:54 UTC, vzdrizhni commented on lib/active_merchant/billing/gateways/abr_russia.rb
> +          elsif (node.to_xml.include?('OrderParams'))
Конечно запрос не проходит, у банка есть определённый список ip, в котором моего нет. Я пробовал через консоль запрос отослать на стейдже, но там ошибку с ssl выдаёт.

2023-08-07 12:24 UTC, Creskiv commented on lib/active_merchant/billing/gateways/abr_russia.rb
> +          elsif (node.to_xml.include?('OrderParams'))
Ну на стейдже у нас оплата работает
Да и всё остальное парсится как надо поэтому мне кажется что все to_xml и прочее лишнее, т.к запросы по одному формату работают

2023-08-07 14:11 UTC, vzdrizhni commented on lib/active_merchant/billing/gateways/abr_russia.rb
> +          elsif (node.to_xml.include?('OrderParams'))
Без to_xml будет сложнее переделать node в обычный хэш и посмотреть какой ответ был. Сравнивать по количеству элементов и их дочерних элементов бессмысленно т.к. их приходит разное количество. Ещё мне нужно переделать массив хэшей в ответе, чтобы удобней доставать rrn, иначе придётся доставать их из массива с помощью find или detect. 
Я создал xml response из примера документации и прогнал его через метод parse. Вот результат:
`{:operation=>"GetOrderInformation", :status=>"00", :Order=>{:row=>{:id=>"477739", :SessionID=>"E60F2F4D759F85D1FA90AE3654C53198", :createDate=>"2019-10-29 12:23:47", :lastUpdateDate=>"2019-10-29 12:30:16", :payDate=>"2019-10-29 12:24:07", :MerchantID=>"99900000", :Amount=>"931", :Currency=>"643", :OrderLanguage=>"RU", :Description=>"testDesc", :ApproveURL=>"https://twpg-shop.abr.ru/index.php?action=handler", :CancelURL=>"https://twpg-shop.abr.ru/index.php?action=handler", :DeclineURL=>"https://twpg-shop.abr.ru/index.php?action=handler", :Orderstatus=>"REVERSED", :Receipt=>nil, :twoId=>"496265998", :RefundAmount=>"0", :RefundCurrency=>"null", :ExtSystemProcess=>"0", :OrderType=>"Purchase", :OrderSubType=>nil, :Fee=>"0", :Email=>nil, :RefundDate=>"0000-00-00 00:00:00", :TWODate=>"191029", :TWOTime=>"122407", :OrderParams=>{:row=>{"PAN"=>"426810******9256", "PGSettings"=>nil, "TWOResponseCode"=>"001", "POS_CAVV"=>"null", "XMLOUT"=>nil, "CardHolderName"=>"L D", "CardBrand"=>"VISA", "RRN"=>"496265983", "APPROVAL"=>"085194", "ResponseDescription"=>"Удачное выполнение транзакции", "recurSlipNumber"=>"0", "InitialRRN"=>"496265983", "OrderPANHash"=>"F951BD8CC1F836DC9D6C4DDCB39882DAF47B5759539D3524FAA8F6901ADBC621", "Response_h"=>"0010011020", "Response_S"=>"477739          ", "CAVV_RC"=>"12", "DescriptionHtml"=>"                    test                ", "feeCalculationResult"=>"0", "POS_eci"=>"87"}}, :OrderOperations=>{:row=>[{:PackageId=>"161", :createDate=>"2019-10-29 12:24:07", :MerchantID=>"99900000", :TERMINALID=>"99900000", :OperType=>"11", :OperName=>"Purchase", :OrderId=>"477739", :Amount=>"931", :Currency=>"643", :Approval=>"085194", :twoId=>"496265983", :twoRC=>"001", :Source=>"0"}, {:PackageId=>"161", :createDate=>"2019-10-29 12:30:16", :MerchantID=>"99900000", :TERMINALID=>"99900000", :OperType=>"21", :OperName=>"Reverse", :OrderId=>"477739", :Amount=>"931", :Currency=>nil, :Approval=>nil, :twoId=>"496265998", :twoRC=>"001", :Source=>"0"}, {:PackageId=>"160", :createDate=>"2019-10-29 12:23:47", :MerchantID=>"99900000", :TERMINALID=>"null", :OperType=>"0", :OperName=>"CreateOrder", :OrderId=>"477739", :Amount=>"0", :Currency=>nil, :Approval=>nil, :twoId=>nil, :twoRC=>nil, :Source=>"0"}]}, :Positions=>{:Position=>{:Quantity=>nil, :Price=>nil, :Tax=>nil, :Text=>nil, :PaymentType=>nil, :PaymentMethodType=>nil, :PaymentSubjectType=>nil}}}}}`
Понятно, что код не укладывается в общую идею, но делать что-то подобное как в блоке else это ад для такой структуры ответа.

2023-08-08 13:30 UTC, vzdrizhni commented on lib/active_merchant/billing/gateways/abr_russia.rb
> +          elsif (node.to_xml.include?('OrderParams'))
В общем проверил на стейдже. Ответ приходит начиная с <Order><row>, а в методе parse он парсится после Response, следовательно parse возвращает пустой хэш т.к. ответ не содержит поля Response. Если не распарсить OrderParams то все строки просто сливаются в одну. Вот пример того что содержится в node:

`<row>
  <id>148711210</id>
  <EncryptedId>CC074DF3D8A52FF6368490F81235A8E2</EncryptedId>
  <SessionID>DF22E014A654071B29C2592C9505F1D3</SessionID>
  <createDate>2023-08-02 19:58:17</createDate>
  <lastUpdateDate>2023-08-02 19:59:22</lastUpdateDate>
  <payDate>2023-08-02 19:59:22</payDate>
  <MerchantID>99280004</MerchantID>
  <TerminalID/>
  <Amount>20000</Amount>
  <Currency>643</Currency>
  <OrderLanguage>RU</OrderLanguage>
  <Description>&#x43A;&#x438;&#x43D;&#x43E;&#x442;&#x435;&#x430;&#x442;&#x440; &#x43C;&#x443;&#x43B;&#x44C;&#x442;&#x438;&#x43F;&#x43B;&#x435;&#x43A;&#x441;, &#x437;&#x430;&#x43B;: &#x417;&#x430;&#x43B; 5, &#x441;&#x435;&#x430;&#x43D;&#x441;: &#x411;&#x430;&#x431;&#x430; &#x42F;&#x433;&#x430;. &#x421;&#x43F;&#x430;&#x441;&#x430;&#x435;&#x442; &#x43C;&#x438;&#x440; 2023-08-04 10:00 / &#x420;&#x44F;&#x434; 7, &#x43C;&#x435;&#x441;&#x442;&#x43E; 14, &#x446;&#x435;&#x43D;&#x430; 200.0 / </Description>
  <ApproveURL>https://meganomkino.secret-agents.ru:/?payment_number=P969249836</ApproveURL>
  <CancelURL>https://meganomkino.secret-agents.ru:/?payment_number=P969249836</CancelURL>
  <DeclineURL>https://meganomkino.secret-agents.ru:/?payment_number=P969249836</DeclineURL>
  <Orderstatus>APPROVED</Orderstatus>
  <Receipt/>
  <twoId>4945863981</twoId>
  <RefundAmount>0</RefundAmount>
  <RefundCurrency/>
  <ExtSystemProcess>0</ExtSystemProcess>
  <OrderType>Purchase</OrderType>
  <OrderSubType/>
  <Fee>0</Fee>
  <Email/>
  <RefundDate>0000-00-00 00:00:00</RefundDate>
  <TWODate>230802</TWODate>
  <TWOTime>195922</TWOTime>
  <OrderParams>
    <row>
      <PARAMNAME>3DS2.MethodURL.Required</PARAMNAME>
      <VAL>true</VAL>
    </row>
    <row>
      <PARAMNAME>APPROVAL</PARAMNAME>
      <VAL>8YN9YH</VAL>
    </row>
    <row>
      <PARAMNAME>ARes.messageExtension</PARAMNAME>
      <VAL>[{"name":"rbaScoring","id":"A00000065801","criticalityIndicator":false,"data":{"totalScore":-224,"ruleSets":[{"ruleSetId":6,"score":0,"description":"Merchant transactions Details"},{"ruleSetId":2,"score":0,"description":"Merchant Account Rules"},{"ruleSetId":4,"score":0,"description":"Client Scoring"},{"ruleSetId":5,"score":-50,"description":"Transaction Scoring"},{"ruleSetId":1,"score":-122,"description":"User Device rules"},{"ruleSetId":3,"score":-52,"description":"Merchant Scoring"}]}}]</VAL>
    </row>
    <row>
      <PARAMNAME>AcqFee</PARAMNAME>
      <VAL>0</VAL>
    </row>
    <row>
      <PARAMNAME>AuthorizationResponseCode</PARAMNAME>
      <VAL>01</VAL>
    </row>
    <row>
      <PARAMNAME>AuthorizedBy3DS2.0</PARAMNAME>
      <VAL>true</VAL>
    </row>
    <row>
      <PARAMNAME>BrowserIP</PARAMNAME>
      <VAL>172.27.84.116</VAL>
    </row>
    <row>
      <PARAMNAME>CardBrand</PARAMNAME>
      <VAL>MIR</VAL>
    </row>
    <row>
      <PARAMNAME>CardHolderName</PARAMNAME>
      <VAL>ROMAN NIKOLAEV</VAL>
    </row>
    <row>
      <PARAMNAME>EncryptedPaymentData</PARAMNAME>
      <VAL/>
    </row>
    <row>
      <PARAMNAME>ExternalResponseCode</PARAMNAME>
      <VAL>00</VAL>
    </row>
    <row>
      <PARAMNAME>ExternalTransactionId</PARAMNAME>
      <VAL>3214007543314008</VAL>
    </row>
    <row>
      <PARAMNAME>InitialExternalTransactionId</PARAMNAME>
      <VAL>3214007543314008</VAL>
    </row>
    <row>
      <PARAMNAME>InitialRRN</PARAMNAME>
      <VAL>321416585422</VAL>
    </row>
    <row>
      <PARAMNAME>InitialTransactionId</PARAMNAME>
      <VAL>4945863981</VAL>
    </row>
    <row>
      <PARAMNAME>Invoice</PARAMNAME>
      <VAL>148711210</VAL>
    </row>
    <row>
      <PARAMNAME>IssCur</PARAMNAME>
      <VAL>643</VAL>
    </row>
    <row>
      <PARAMNAME>IssCurText</PARAMNAME>
      <VAL>&#x20BD;</VAL>
    </row>
    <row>
      <PARAMNAME>IssFee</PARAMNAME>
      <VAL>0</VAL>
    </row>
    <row>
      <PARAMNAME>MPI.PAReq.xid</PARAMNAME>
      <VAL>f513722f-9fdb-46f8-801a-fddf76bca26a</VAL>
    </row>
    <row>
      <PARAMNAME>MPI.PARes.cavv</PARAMNAME>
      <VAL>AAQBABCZRAAAAAOWQ5lEAa5yqwg=</VAL>
    </row>
    <row>
      <PARAMNAME>MPI.PARes.eci</PARAMNAME>
      <VAL>02</VAL>
    </row>
    <row>
      <PARAMNAME>MPI.PARes.status</PARAMNAME>
      <VAL>Y</VAL>
    </row>
    <row>
      <PARAMNAME>MPI.Version</PARAMNAME>
      <VAL>2</VAL>
    </row>
    <row>
      <PARAMNAME>Network</PARAMNAME>
      <VAL>44</VAL>
    </row>
    <row>
      <PARAMNAME>OrderPANHash</PARAMNAME>
      <VAL>613ADC5C8952E3AEB59150C78DE860765ACBD746047E18C9F0FA170070397E5E</VAL>
    </row>
    <row>
      <PARAMNAME>PAN</PARAMNAME>
      <VAL>220015******2124</VAL>
    </row>
    <row>
      <PARAMNAME>POS_CAVV</PARAMNAME>
      <VAL>f513722f9fdb46f8801afddf76bca26a0000000000040100109944000000039643994401AE72AB08</VAL>
    </row>
    <row>
      <PARAMNAME>POS_eci</PARAMNAME>
      <VAL>82</VAL>
    </row>
    <row>
      <PARAMNAME>RRN</PARAMNAME>
      <VAL>321416585422</VAL>
    </row>
    <row>
      <PARAMNAME>RefURL</PARAMNAME>
      <VAL>https://ais_widget.secret-agents.ru/</VAL>
    </row>
    <row>
      <PARAMNAME>ResponseCodeCategory</PARAMNAME>
      <VAL>0</VAL>
    </row>
    <row>
      <PARAMNAME>ResponseDescription</PARAMNAME>
      <VAL>&#x423;&#x434;&#x430;&#x447;&#x43D;&#x43E;&#x435; &#x432;&#x44B;&#x43F;&#x43E;&#x43B;&#x43D;&#x435;&#x43D;&#x438;&#x435; &#x442;&#x440;&#x430;&#x43D;&#x437;&#x430;&#x43A;&#x446;&#x438;&#x438;</VAL>
    </row>
    <row>
      <PARAMNAME>TWOResponseCode</PARAMNAME>
      <VAL>001</VAL>
    </row>
    <row>
      <PARAMNAME>Tds2DirectoryId</PARAMNAME>
      <VAL>MIR</VAL>
    </row>
    <row>
      <PARAMNAME>TdsVersion</PARAMNAME>
      <VAL>2</VAL>
    </row>
    <row>
      <PARAMNAME>XMLOUT</PARAMNAME>
      <VAL>
        <XMLOut>
          <Message date="02/08/2023 19:59:22">
            <Version>1.0</Version>
            <Currency>643</Currency>
            <ResponseCode>001</ResponseCode>
            <SessionId>DF22E014A654071B29C2592C9505F1D3</SessionId>
            <Brand>MIR</Brand>
            <RRN>321416585422</RRN>
            <PAN>220015XXXXXX2124</PAN>
            <Fee>0</Fee>
            <CardHolderName>ROMAN NIKOLAEV</CardHolderName>
            <OrderID>148711210</OrderID>
            <SessionID>DF22E014A654071B29C2592C9505F1D3</SessionID>
            <TransactionType>Purchase</TransactionType>
            <OrderDescription>&#x43A;&#x438;&#x43D;&#x43E;&#x442;&#x435;&#x430;&#x442;&#x440; &#x43C;&#x443;&#x43B;&#x44C;&#x442;&#x438;&#x43F;&#x43B;&#x435;&#x43A;&#x441;, &#x437;&#x430;&#x43B;: &#x417;&#x430;&#x43B; 5, &#x441;&#x435;&#x430;&#x43D;&#x441;: &#x411;&#x430;&#x431;&#x430; &#x42F;&#x433;&#x430;. &#x421;&#x43F;&#x430;&#x441;&#x430;&#x435;&#x442; &#x43C;&#x438;&#x440; 2023-08-04 10:00 / &#x420;&#x44F;&#x434; 7, &#x43C;&#x435;&#x441;&#x442;&#x43E; 14, &#x446;&#x435;&#x43D;&#x430; 200.0 / </OrderDescription>
            <ApprovalCode>8YN9YH A</ApprovalCode>
            <ApprovalCodeScr>8YN9YH</ApprovalCodeScr>
            <PurchaseAmount>20000</PurchaseAmount>
            <PurchaseAmountScr>200.00</PurchaseAmountScr>
            <TotalAmount>20000</TotalAmount>
            <TotalAmountScr>200.00</TotalAmountScr>
            <FeeScr>0.00</FeeScr>
            <AcqFee>0</AcqFee>
            <AcqFeeScr>0.00</AcqFeeScr>
            <CurrencyScr>&#x420;&#x43E;&#x441;&#x441;&#x438;&#x439;&#x441;&#x43A;&#x438;&#x439; &#x440;&#x443;&#x431;&#x43B;&#x44C;</CurrencyScr>
            <CurrencyISOAlpha>RUB</CurrencyISOAlpha>
            <TranDateTime>02/08/2023 19:59:22</TranDateTime>
            <ResponseDescription>&#x423;&#x434;&#x430;&#x447;&#x43D;&#x43E;&#x435; &#x432;&#x44B;&#x43F;&#x43E;&#x43B;&#x43D;&#x435;&#x43D;&#x438;&#x435; &#x442;&#x440;&#x430;&#x43D;&#x437;&#x430;&#x43A;&#x44 [...]

2023-08-09 07:16 UTC, Creskiv approved these changes

2023-08-09 07:16 UTC, merged